openapi: 3.0.1
info:
  title: filesStore
  version: "3.6"
servers:
  - url: https://ptai.domain.org:443/
security:
  - Bearer: []
paths:
  '/api/Store/sources/{projectId}':
    post:
      tags:
        - Store
      operationId: UploadSources
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  nullable: true
            encoding:
              file:
                style: form
      responses:
        '200':
          description: Success
components:
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
