openapi: 3.0.1
info:
  title: gateway
  version: "3.6"
servers:
  - url: https://ptai.domain.org:443/
security:
  - Bearer: []
paths:
  /api/AgentAuth/signin:
    get:
      tags:
        - AgentAuth
      parameters:
        - name: scopeType
          in: query
          schema:
            $ref: '#/components/schemas/AuthScopeType'
      responses:
        '200':
          description: Success
components:
  schemas:
    AuthScopeType:
      enum:
        - None
        - Agent
        - Viewer
        - Internal
        - Web
        - WebRefresh
        - WebLongRefresh
        - AccessToken
        - AccessTokenRefresh
      type: string
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
