connections:
  ptai411: &current
    version: V411
    url: https://ptai411-server.domain.org:443
    # CI only API token
    token: CI_TOKEN_GOES_HERE
    # CI and agent API token
    failSafeToken: CI_AND_AGENT_TOKEN_GOES_HERE
    user: root
    password: PASSWORD
    ca: keys/domain.org.pem
    insecure: false
  ptai420:
    version: V420
    url: https://ptai420-server.domain.org:443
    # CI only API token
    token: CI_TOKEN_GOES_HERE
    # CI and agent API token
    failSafeToken: CI_AND_AGENT_TOKEN_GOES_HERE
    user: root
    password: PASSWORD
    ca: keys/domain.org.pem
    insecure: false
current: *current
