connections:
  ptai411: &current
    version: V411
    url: https://ptai411-server.domain.org:443
    # CI only API token
    token: c/1qJI1UC1jfDJ9VZXQSY1qer9dbkFry
    # CI and agent API token
    failSafeToken: z9Ha3BxcsLFWC/+keAUpbEgniZScABpb
    user: root
    password: P@ssw0rd
    ca: keys/domain.org.pem
    insecure: false
current: *current
