openapi: 3.0.1
info:
  title: systemManagement
  version: 1.0.0
servers:
  - url: https://ptai41.domain.org:443/
security:
  - Bearer: []
paths:
  /api/logs:
    get:
      tags:
        - Logs
      summary: Get server`s logs
      parameters:
        - name: dateFrom
          in: query
          description: Date from
          schema:
            type: string
            format: date-time
        - name: dateTo
          in: query
          description: Date to
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Success
          content:
            application/zip: {}
        '401':
          description: Unauthorized
  /health/summary:
    get:
      tags:
        - HealthCheck
      summary: Health check of services. Response time in milliseconds
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckSummaryResult'
components:
  schemas:
    HealthCheckServiceResult:
      type: object
      properties:
        Service:
          type: string
          nullable: true
        Status:
          $ref: '#/components/schemas/HealthStatus'
        ResponseTime:
          type: number
          format: double
      additionalProperties: false
    HealthCheckSummaryResult:
      type: object
      properties:
        TotalResponseTime:
          type: number
          format: double
        Services:
          type: array
          items:
            $ref: '#/components/schemas/HealthCheckServiceResult'
          nullable: true
      additionalProperties: false
    HealthStatus:
      enum:
        - Unhealthy
        - Degraded
        - Healthy
      type: string
      format: ''
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
