connections:
  ptai36: &current
    version: V36
    url: https://ptai.domain.org:443/
    token: TOKEN_GOES_HERE
    user: Administrator
    password: PASSWORD
    ca: keys/domain.org.pem
    insecure: false

current: *current
