openapi: 3.0.1
info:
  title: authService
  version: "1.0"
servers:
  - url: https://127.0.0.1:443/
paths:
  /api/Auth/signin:
    get:
      tags:
        - Auth
      summary: Login user by NTLM or client certificate in request headers
      operationId: SignIn
      parameters:
        - name: scopeType
          in: query
          schema:
            type: string
            enum:
              - None
              - Agent
              - Viewer
              - Internal
              - Web
              - WebRefresh
              - WebLongRefresh
      responses:
        200:
          description: Returns the created JWT token
          content:
            application/json:
              schema:
                type: string
        401:
          description: Unauthorized
          content: {}
  /api/Auth/refreshToken:
    get:
      tags:
        - Auth
      summary: Refresh token
      operationId: RefreshToken
      responses:
        200:
          description: Returns the created JWT token
          content: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorModel'
  /api/Auth/validateToken:
    post:
      tags:
        - Auth
      operationId: ValidateToken
      responses:
        200:
          description: Success
          content: {}
components:
  schemas:
    ApiErrorModel:
      type: object
      properties:
        errorCode:
          type: string
          readOnly: true
          enum:
            - None
            - INCORRECT_USER_AND_PASSWORD
            - USER_SID_IS_EMPTY
            - MEMBER_ALREADY_EXISTS
            - PROJECT_ROLE_PERMISSIONS_ALREADY_EXISTS
            - UPDATE_PACKAGE_INVALID_CHECK_SUM
            - UPDATE_PACKAGE_VERSION_IS_ALREADY_UPLOADED
            - UPDATE_PACKAGE_UPLOADED_IS_ALREADY_STARTED
            - UPDATE_PACKAGE_UNKNOWN_PRODUCT
            - UPDATE_PACKAGE_VERSION_INVALID
            - UPDATE_PACKAGE_VERSION_IS_NOT_UPLOADED
            - UPDATE_SERVER_PROCESS_RUN_TIMEOUT
            - UPDATE_SERVER_PARAMETERS_ARE_NOT_FILLED
            - UPDATE_SERVER_PARAMETERS_INVALID
            - UPDATE_SERVER_INSTALLER_EXIT_WITH_ERROR
            - CERTIFICATE_FILE_IS_EMPTY
            - CERTIFICATE_IS_ALREADY_INSTALLED
            - CERTIFICATE_IS_NOT_VALID
            - PROJECT_WITH_SAME_NAME_ALREADY_EXISTS
            - ISSUE_TRACKER_CONNECTION_NOT_FOUND
            - ISSUE_TRACKER_CONNECTION_SETTINGS_NOT_SET
            - ISSUE_TRACKER_SETTINGS_ID_NOT_SET
            - ISSUE_TRACKER_CREDENTIALS_NOT_SET
            - ISSUE_TRACKER_HOST_IS_INCORRECT
            - ISSUE_TRACKER_OAUTH_DATA_NOT_SET
            - ISSUE_TRACKER_TRACKER_NOT_FOUND
            - ISSUE_TRACKER_TRACKER_NOT_FOUND_WITH_OAUTH
            - ISSUE_TRACKER_INVALID_TICKET_LINK
            - ISSUE_TRACKER_IMPOSSIBLE_SKIP_UPDATE_CREDENTIALS
            - ISSUE_TRACKER_UNSUPPORTED_FIELDS_COFIGURATION
            - ISSUE_TRACKER_TICKET_CREATION_FAILED
            - ISSUE_TRACKER_PRIORITIES_GETTING_FAILED
            - ISSUE_TRACKER_USERS_GETTING_FAILED
            - ISSUE_TRACKER_STATUSES_GETTING_FAILED
            - ISSUE_TRACKER_FIELDS_GETTING_FAILED
            - ISSUE_TRACKER_OPTIONS_GETTING_FAILED
            - ISSUE_TRACKER_EXISTING_TICKETS_GETTING_FAILED
            - ISSUE_TRACKER_COMPONENTS_GETTING_FAILED
            - ISSUE_TRACKER_CAPTCHA_CHALLENGE
            - ISSUE_TRACKER_AUTHENTICATION_DENIED_DETAILED
            - ISSUE_TRACKER_AUTHENTICATION_DENIED
            - ISSUE_TRACKER_AUTHENTICATION_FAILED
            - ISSUE_ATTACH_TICKET_LINK_FAILED
            - COMMENT_POLICY_FAILED_COMMENT_IS_EMPTY
            - PROJECTS_COUNT_LIMITED_BY_LICENSE
            - LICENSE_FILE_IS_INVALID
            - LICENSE_FINGERPRINT_ERROR
        details:
          type: object
          additionalProperties:
            type: string
          readOnly: true
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert JWT with Bearer into field
      name: Authorization
      in: header
