spring:
  jpa:
    hibernate.ddl-auto: none
  liquibase:
    contexts: test
  h2:
    console:
      enabled: true
server:
  port: 18443
management:
  endpoint:
    health.enabled: true

ptai-integration-server:
  # URL of PTAI server gateway. This is a fake value as during integration tests phase
  # the real value is to be read from consul
  ptai-gateway-url: https://ptaisrv.domain.net:443
