name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build - Java 8
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ptai-ee-tools
          path: |
            ptai-jenkins-plugin/build/libs/*/ptai-jenkins-plugin.hpi
            ptai-teamcity-plugin/ptai-teamcity-plugin-server/build/distributions/*/ptai-teamcity-plugin.zip
            ptai-cli-plugin/build/libs/*/ptai-cli-plugin.jar